<!-- begin error -->
<div class="error">
    <div class="error-code m-b-10">403 <i class="fa fa-warning"></i></div>
    <div class="error-content">
        <div class="error-message">Доступ запрещён</div>
        <div class="error-desc m-b-20">
            Страница, на которую вы хотите попасть, требует определённых прав. <br />
        </div>
        <div class="row">
            <div class="col-md-2">
                <a href="<?=$this->url('home')?>" class="btn btn-success">
                   <?=$this->translate('on_basic')?></a>
            </div>
        </div>
    </div>
</div>
<!-- end error -->