<div class="c-12">
   <ul>
      <? foreach($this->container as $i){ ?>
         <li>
            <a href="<?=$i->getHref()?>">
               <?=$this->escapeHtml($i->getLabel())?>
            </a>
            <? if(count($i)){ ?>
               <ul>
                  <? foreach($i as $ii){ ?>
                     <li>
                        <a href="<?=$ii->getHref()?>">
                           <?=$this->escapeHtml($ii->getLabel())?>
                        </a>
                     </li>
                  <? } ?>
               </ul>
            <? } ?>
         </li>
      <? } ?>
   </ul>
</div>
