<?php
use Application\Model\Recaptcha;

$this->inlineScript()
   ->appendFile('//www.google.com/recaptcha/api.js')
;

$article = $this->article;
?>

<h1><?=$article['title']?></h1>

<div id="cont">
   <?=$article['text']?>
</div>
<hr>
<h2>Добавить комментарий</h2>
<div>
   <? $f = $this->form_site_comment;
   echo $this->form()->openTag($f);
   foreach($f as $el){
      if($el->getName() == 'submit'){?>
         <div class="g-recaptcha"
              data-sitekey="<?=Recaptcha::KEY?>"></div>
      <? }
      echo $this->formRow($el);
   }
   echo $this->form()->closeTag();
   ?>
</div>
<hr>

<div>
   <? if(count($this->comments)){?>
      <? foreach($this->comments as $comment){?>
         <div>
            <p>
               <?=date('d.m.Y H:i', strtotime($comment['date']))?>
               <?=$this->escapeHtml($comment['name'])?>
            </p>
            <?=$this->escapeHtml($comment['text'])?>
         </div>
      <? }?>
   <? }
   else{?>
      <p>Пока нет комментариев.</p>
   <? }?>
   
</div>