<?
use Zend\Form\Element\Select;
use Application\Model\Orders;

$types = Orders::getTypes();
$p = $this->params;
$type = $this->type;
$kind = empty($p['kind'])? 'all': $p['kind'];
list($k, $d) = explode(' ', $types[$type], 2);

$this->headTitle('галерея работ конкурсов '.$d);
$this->headMeta()
   ->appendName('keywords', 'Галерея работ диплом без регистрации '.
      $d.' дистанционные творческие бесплатно'
   )
   ->appendName('description', 'Галерея работ Всероссийских дистанционных 
   творческих конкурсов '.$d)
   ->appendName('robots', 'index, follow')
;
$this->inlineScript()
   ->appendFile('/js/index/gallery.js');
$this->headLink()
   ->appendStylesheet('/css/index/gallery.css');
?>

<script>
   var vars = {
      type: '<?=$type?>'
   }
</script>



<div id="home">
   <div id="left_col"></div>
   <div id="right_col"></div>
   <div id="wrap">
      <h1>Галерея работ конкурсов <?=$d?></h1>
      <div>
         <div class="title">
            Тип конкурса
         </div>
         <? foreach($types as $k => $v){
            ?>
            <div class="inp">
               <a href="<?=$this->url('gallery', ['page' => 1,
                                                  'type' => $k]
               )?>">
                  <div class="button <?=$type == $k? 'active': ''?>">
                     <?=$v?>
                  </div>
               </a>
            </div>
         <? } ?>
      </div>
      <div>
         <div class="title">
            Номинация
         </div>
         <div class="inp">
            <? $nominations = [0 => 'Все номинации'] + 
               array_column($this->nominations, 'title', 'id'); 
            $select = new Select('nomination');
            $select->setValueOptions($nominations);
            $select->setValue(empty($p['nomination'])? 0: $p['nomination']);
            echo $this->formElement($select);
            ?>
         </div>
      </div>
      <? if(count($this->themes)){ ?>
         <div>
            <div class="title">
               Тема конкурса
            </div>
            <div class="inp">
               <? $themes = [0 => 'Все номинации'] + 
                  array_column($this->themes, 'title', 'id');
               $select = new Select('theme');
               $select->setValueOptions($themes);
               $select->setValue(empty($p['theme'])? 0: $p['theme']);
               echo $this->formElement($select);
               ?>
            </div>
         </div>
      <? } ?>
      <div class="clear"></div>
      <div id="gallery_field"></div>
      <div id="loading">
         <img src="<?=$this->basePath('images/ajax-loader.gif')?>" alt="">
      </div>

   </div>
</div>
