<?php
$this->headLink()
;
$this->inlineScript()
   ->appendFile($this->basePath('/js/tinymce/tinymce.min.js'))
   ->appendFile($this->basePath('/js/tinymce/langs/ru.js'))
   ->appendFile($this->basePath('/js/user/site-index.js'))
;

?>

<div id="home">
   <div id="left_col"></div>
   <div id="right_col"></div>
   <div id="wrap">
      <h1>
         <?=$this->is_edit? 'Редактирование статьи блога':
         'Добавление статьи блога'?>
      </h1>

      <? $f = $this->form_site_pages;
      echo $this->form()->openTag($f);
      foreach($f as $el) echo $this->formRow($el);
      echo $this->form()->closeTag();
      ?>
   </div>
</div>
